const data = [
  { q: "Selon Jean 14:6, qui est le chemin, la vérité et la vie ?", a: ["Moïse", "Jésus-Christ", "Paul", "Un ange"], ok: 1, exp: "Jésus déclare Lui-même qu’Il est le chemin, la vérité et la vie. Nul ne vient au Père que par Lui." },
  { q: "Selon Éphésiens 2:8-9, le salut est reçu par...", a: ["la foi", "l’argent", "la réputation", "la force humaine"], ok: 0, exp: "La Bible enseigne que nous sommes sauvés par grâce, par le moyen de la foi, et non par les œuvres." },
  { q: "Que signifie se repentir ?", a: ["Changer de pays", "Se tourner vers Dieu en abandonnant le péché", "Avoir seulement peur", "Accuser les autres"], ok: 1, exp: "La repentance biblique implique un retour sincère vers Dieu et un abandon du chemin du péché." },
  { q: "Qui donne la vie éternelle ?", a: ["Jésus-Christ", "Un objet religieux", "Un esprit inconnu", "Une consultation"], ok: 0, exp: "La vie éternelle est donnée par Jésus-Christ à ceux qui croient en Lui." }
];
let index = -1; let score = 0; let answered = false;
const quiz = document.getElementById('quiz'); const next = document.getElementById('next'); const scoreBox = document.getElementById('score');
function render(){ answered=false; const item=data[index]; quiz.innerHTML = `<div class="question">${index+1}. ${item.q}</div><div class="answers">${item.a.map((x,i)=>`<button data-i="${i}">${x}</button>`).join('')}</div><div id="feedback"></div>`; document.querySelectorAll('.answers button').forEach(btn=>btn.addEventListener('click',()=>choose(Number(btn.dataset.i)))); next.textContent = index === data.length-1 ? 'Voir le résultat' : 'Question suivante'; next.classList.add('hidden'); }
function choose(i){ if(answered)return; answered=true; const item=data[index]; if(i===item.ok){score++; document.getElementById('feedback').innerHTML=`<p class="ok">Bonne réponse.</p><p class="explain">${item.exp}</p>`;} else {document.getElementById('feedback').innerHTML=`<p class="bad">Réponse incorrecte.</p><p class="explain">La bonne réponse était : <strong>${item.a[item.ok]}</strong>. ${item.exp}</p>`;} next.classList.remove('hidden'); }
next.addEventListener('click',()=>{ index++; if(index>=data.length){ quiz.innerHTML = `<h2>Résultat final</h2><p class="question">Score : ${score}/${data.length}</p><p class="explain">Continue à méditer la Parole de Dieu. Le but n’est pas seulement de gagner, mais de connaître Christ et d’obéir à Sa Parole.</p>`; next.textContent='Recommencer'; next.onclick=()=>location.reload(); return;} render(); });
